######################################################################
# Automatically generated by qmake (2.00a) Sáb Dez 10 21:34:13 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += cronometro.cpp
